### ISSUE TITLE
Eclipse doesn't restart after installing a plugin

### ISSUE THREAD

**Issue by soisik** [lalmeras/eclipse.builder#1]
Reproduced with java 9, 10, 11

1. install plugin
2. restart eclipse
3. eclipse does't restart and display a error message in log : RuntimeException: Application “” could not be found in the registry.

This fixed the issue for me : https://stackoverflow.com/a/12678359, I could restart eclipse after adding values to configuration/config.ini

**Comment by lalmeras** [comment]
It is also broken with Java 8.

**Comment by lalmeras** [comment]
I think I find the issue. When I install plugins during packaging, I uninstall all features, then reinstall all features and added plugins (this is the way to perform plugin installation and upgrade on command line).

This step must broke epp.package.jee, and it is the product missing in config.ini after a manual plugin installation.

Also just find that I already protect epp.package.{rcp,java}, and that releases <= oxygen are eclipse-java based, and releases >= photon are jee based.

I'm checking that fixing PROTECTED_FEATURES in feature.py fix the issue.

**Comment by lalmeras** [comment]
@soisik I reopen and wait for your confirmation about this fix.

**Comment by soisik** [comment]
all good for me, thank for the prompt fix !
